config/routes.rb
Rails.application.routes.draw do

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'
  get '/register', to: 'registration#new'
  post '/register/create', to: 'registration#create', as: :registration
  resources :photos, only: [:show, :update, :edit], constraints: { id: /[^\/]+/ }
  get '/profiles/me/', to: 'profiles#show_self'
  resources :profiles, only: [:show, :update, :edit], constraints: { id: /[^\/]+/ }
  post '/profiles/:id/view-settings', to: 'profiles#update_view_setting', constraints: { id: /[^\/]+/ }, as: :update_view_setting
  patch '/profiles/:id/view-settings', to: 'profiles#update_view_setting', constraints: { id: /[^\/]+/ }
  get '/profile/show/uid/:id', to: redirect('/profiles/%{id}'), constraints: { id: /[^\/]+/ }
  get '/profile/show/virid/:id', to: 'profiles#show_by_id', constraints: { id: /\d+/ }

  get '/photo/raw', to: 'raw_photos#show'
  post '/photo/raw', to: 'raw_photos#update'

  get '/search', to: 'search#search'
  get '/search/suggest', to: 'search#suggest'
  get '/search/suggest_leader', to: 'search#suggest_leader'

  get '/svie/edit', to: 'svie#edit'
  post '/svie/update', to: 'svie#update'
  post '/svie/destroy', to: 'svie#destroy'
  post '/svie/outside', to: 'svie#outside'
  post '/svie/inside', to: 'svie#inside'
  resources :svie, only: %i[index new create]
  get '/svie/pdf', to: 'svie#application_pdf'
  get '/svie/hierarchy', to: 'svie#hierarchy'

  get '/judgement', to: 'judgements#index', as: :judgements
  get '/judgement/:evaluation_id', to: 'judgements#show', as: :judgement
  post '/judgement/:evaluation_id/update', to: 'judgements#update', as: :update_judgement

  root to: redirect('/profiles/me')
  resources :entry_requests do
    get :review, on: :collection
    put :update_review, on: :member
  end
  get 'groups/all', to: 'groups#all', as: :all_groups
  resources :groups, only: [:show, :index, :edit, :update, :create, :new] do
    resources :sub_groups do
      post :join, on: :member
      delete :leave, on: :member
      post :set_admin, on: :member
      resources :sub_group_principles, as: :principles ,only: [:index, :update, :create, :destroy]
      resources :sub_group_evaluations, as: :evaluation do
        get :table
      end
    end
    resources :memberships, only: [:create, :destroy] do
      post '/inactivate', to: 'memberships#inactivate'
      post '/reactivate', to: 'memberships#reactivate'
      post '/accept', to: 'memberships#accept'
      post :withdraw, on: :member
      put '/archive', to: 'memberships#archive'
      put '/unarchive', to: 'memberships#unarchive'
      resources :posts, only: [:index, :create, :destroy]
    end

    get '/group_posts', to: "posts#group_posts", as: :posts
    resources :post_types, only: [:index, :create, :destroy]

    get '/evaluations/current', to: 'evaluations#current'
    resources :evaluations, only: [:index, :show, :edit, :update] do
      resources :principles, only: [:index, :update, :create, :destroy]
      post '/pointdetails/update', to: 'point_details#update'
      resources :point_detail_comments, shallow: true, only: %i[index create update edit destroy]
      post '/entryrequests', to: 'evaluations#submit_entry_request'
      delete '/entryrequests', to: 'evaluations#cancel_entry_request', as: :cancel_entry_request
      post '/entryrequests/update', to: 'entry_requests#update'
      get '/justifications/edit', to: 'justifications#edit'
      post '/justifications/update', to: 'justifications#update'
      get '/table', to: 'evaluations#table'
      post '/pointrequest', to: 'evaluations#submit_point_request'
      delete '/pointrequest', to: 'evaluations#cancel_point_request', as: :cancel_point_request
      post :copy_previous_principles
    end

    get '/messages', to: 'messages#index'
    get '/messages/all', to: 'messages#all'
    post '/messages', to: 'messages#create'
    get '/delegates', to: 'delegates#show'
    post '/delegate', to: 'delegates#create'
    delete '/delegate', to: 'delegates#destroy'
    get '/history', to: 'group_history#show'
  end

  get '/korok/showgroup/id/:id', to: redirect('/groups/%{id}')

  post '/privacies/update', to: 'privacies#update'

  resources :im_accounts, only: [:create, :update, :destroy]

  namespace :admin do
    get 'delegates/count', to: 'delegates#count'
    get 'delegates/export', to: 'delegates#export'
    get 'delegates', to: 'delegates#index'
    post 'delegates/update', to: 'delegates#update'

    resources :svie, only: [:index]
    post '/svie/approve/:id', to: 'svie#approve', as: :svie_approve
    post '/svie/reject/:id', to: 'svie#reject', as: :svie_reject

    resources :rvt_helpers, only: [:index] do
      post :add, on: :member
      post :remove, on: :member
    end
  end

  get '/seasons', to: 'season_admin#index', as: :seasons
  get '/seasons/export_point_history', to: 'season_admin#export_point_history', as: :export_point_history
  get '/seasons/export_entry_requests', to: 'season_admin#export_entry_requests', as: :export_entry_requests
  get '/seasons/export_active_users', to: 'season_admin#export_active_users', as: :export_active_users
  post '/seasons/next', to: 'season_admin#next', as: :next_semester
  post '/seasons/previous', to: 'season_admin#previous', as: :previous_semester
  post '/seasons', to: 'season_admin#update'

  if Rails.env.development? || Rails.env.staging?
    get '/development', to: 'development#index'
    post '/development/impersonate/random', to: 'development#impersonate_someone', as: :impersonate_someone
    post '/development/impersonate/user', to: 'development#impersonate_user', as: :impersonate_user
    post '/development/impersonate/role', to: 'development#impersonate_role', as: :impersonate_role
  end

  get '/services/sync/:id', to: 'auth_sch_services#sync'
  get '/services/sync/:id/memberships', to: 'auth_sch_services#memberships'
  get '/services/entrants/get/:semester/:id', to: 'auth_sch_services#entrants'
  get '/services/entrants/get/:semester/authsch/:id', to: 'auth_sch_services#entrants'

  notify_to :users

end

app/controllers/judgement_controller.rb
class JudgementController < ApplicationController
  before_action :require_login
  before_action :require_privileges_of_rvt

  def index
    semester = SystemAttribute.semester.to_s
    @evaluations = Evaluation.where(date: semester).page(params[:page]).decorate
  end

  def show
    @evaluation = Evaluation.find(params[:evaluation_id])
    @point_details = PointDetail.includes(:point_request)
      .select { |pd| pd.point_request.evaluation == @evaluation }
    @evaluation_messages = EvaluationMessage.where(group: @evaluation.group)
      .order(sent_at: :desc).page(params[:page]).decorate
    @entry_requests = EntryRequestDecorator.decorate_collection(@evaluation
      .entry_requests.select { |er| er.entry_type != EntryRequest::KDO })
  end

  def update
    unless SystemAttribute.evaluation_season?
      return redirect_back fallback_location: judgements_path, alert: t(:not_evaluation_season)
    end
    evaluation = Evaluation.find(params[:evaluation_id])
    success = CreateJudgement.call(evaluation, judgement_params)
    if success
      redirect_back fallback_location: judgements_path, notice: t(:edit_successful)
    else
      redirect_back fallback_location: judgements_path, alert: t(:no_changes)
    end
  end

  private
    def judgement_params
      params.permit(:entry_request_status, :point_request_status, :explanation)
    end

end

app/controllers/judgements_controller.rb
class JudgementsController < ApplicationController

  def index
    authorize Evaluation.new, policy_class: JudgementPolicy

    @evaluations = Evaluation.where(date: current_semester).includes(:group)
    if params[:resort_id].to_i == -1
      resortless_evaluation_ids = @evaluations.reject { |e| e.group.parent&.resort? || e.group.resort? }
                                              .map(&:id)
      @evaluations = @evaluations.where(id: resortless_evaluation_ids)
    elsif Group.exists?(params[:resort_id].to_i)
      @evaluations = @evaluations.where(group_id: groups_in_resort(params[:resort_id]).ids)
    end
    @evaluations = @evaluations.page(params[:page]).decorate

    @resorts = Group.resorts.order(:name)
  end

  def show
    @evaluation = Evaluation.includes(:principles).find(params[:evaluation_id])
    authorize @evaluation, policy_class: JudgementPolicy

    @point_details = PointDetail.includes(%i[point_request principle])
                                .select { |pd| pd.point_request.evaluation_id == @evaluation.id }
    @evaluation_messages =
      EvaluationMessage.where(group: @evaluation.group, semester: current_semester)
                       .order(sent_at: :desc).page(params[:page]).decorate
    @entry_requests = @evaluation.entry_requests.order(:entry_type).reject { |er| er.entry_type == EntryRequest::KDO }
    @entry_requests = EntryRequestDecorator.decorate_collection @entry_requests
    @users = User.joins(point_requests: :evaluation)
                 .where(evaluations: { id: params[:evaluation_id] })
                 .where.not(point_requests: { point: 0 })
                 .includes(:entry_requests, point_requests: [point_details: :principle])
                 .sort_by(&:full_name)
    @users = EvaluationUserDecorator.decorate_collection(@users, context: { evaluation: @evaluation })
    @evaluation_point_calculator = EvaluationPointCalculator.new(@users)
    @users = @users.sort { |a, b| hu_compare(a.full_name, b.full_name) }
  end

  def update
    evaluation = Evaluation.find(params[:evaluation_id])
    authorize evaluation, policy_class: JudgementPolicy

    create_judgement_service = CreateJudgement.new(judgement_params, evaluation, current_user)
    begin
      create_judgement_service.call
    rescue CreateJudgement::NoChangeHaveBeenMade
      redirect_back fallback_location: judgements_path, alert: t(:no_changes)
      return
    rescue CreateJudgement::UserCantMakeTheRequestedUpdates
      raise Pundit::NotAuthorizedError
    end

    redirect_back fallback_location: judgements_path, notice: t(:edit_successful)
  end

  private

  def groups_in_resort(resort_id)
    Group.where(parent_id: resort_id).or(Group.where(id: resort_id))
  end

  def groups_outside_resorts
    Group.where(parent_id: resort_id).or(Group.where(id: resort_id))
  end

  def judgement_params
    params.permit(:entry_request_status, :point_request_status, :explanation)
  end
end

app/helpers/judgements_helper.rb
module JudgementsHelper
  def work_points_sum(point_details, users)
    points(point_details, users, method(:sum_work_details)).sum
  end

  def responsibility_points_sum(point_details, users)
    points(point_details, users, method(:sum_responsibility_details)).sum
  end

  def all_points_sum(point_details, users)
    points(point_details, users, method(:sum_all_details)).sum
  end

  def work_points_average(point_details, users)
    average(points(point_details, users, method(:sum_work_details)))
  end

  def responsibility_points_average(point_details, users)
    average(points(point_details, users, method(:sum_responsibility_details)))
  end

  def all_points_average(point_details, users)
    average(points(point_details, users, method(:sum_all_details)))
  end

  private

  def points(point_details, users, method)
    points = []
    users.each do |user|
      sum = method.call(point_details, user)
      points.push sum if sum.positive?
    end
    points
  end

  def average(points_array)
    return 0 if points_array.empty?

    average = points_array.sum / points_array.size.to_f
    average.round(2)
  end
end

app/views/judgements/_entry_requests.html.erb
<ul class="uk-list uk-list-striped">
  <li class="uk-grid uk-margin-remove uk-text-bold">
    <div class="uk-width-2-10">
      Név
    </div>
    <div class="uk-width-1-10 uk-text-center">
      Típus
    </div>
    <div class="uk-width-6-10 uk-text-center">
      Leírás
    </div>
  </li>

  <% @entry_requests.each do |entry_request| %>
    <li class="uk-grid uk-margin-remove">
      <div class="uk-width-2-10">
        <%= entry_request.user.decorate.full_name %>
      </div>
      <div class="uk-width-1-10 uk-text-center">
        <%= entry_request.nice_entry_type %>
      </div>
      <div class="uk-width-6-10 uk-text-center">
        <%= entry_request.justification %>
      </div>
    </li>
  <% end %>
</ul>

app/views/judgements/_evaluation_messages.html.erb
<%= render 'messages/form', group: @evaluation.group %>

<% if @evaluation_messages.empty? %>
  <div class="uk-text-center uk-padding uk-text-muted">
    Nincs megjelenítendő üzenet!
  </div>
<% else %>
  <ul class="uk-comment-list uk-margin-top">
    <% @evaluation_messages.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
  </ul>
<% end %>

<div class="uk-width-expand uk-text-center uk-margin-top">
  <%= paginate @evaluation_messages %>
</div>

app/views/judgements/_form.html.erb
<%= form_tag update_judgement_path, class: 'uk-form uk-form-horizontal uk-width-1-1 uk-width-large-1-2 uk-align-center' do %>
  <div class="uk-form-row">
    <label class="uk-form-label">Pont igénylés:</label>
    <div class="uk-form-controls">
      <%= select_tag :point_request_status,
          options_for_select(Rails.configuration.x.evaulation_request_statuses.invert, evaluation.point_request_status),
          class: 'uk-select uk-width-1-1' %>
    </div>
  </div>

  <div class="uk-form-row">
    <label class="uk-form-label">Belépő igénylés:</label>
    <div class="uk-form-controls">
      <%= select_tag :entry_request_status,
          options_for_select(Rails.configuration.x.evaulation_request_statuses.invert, evaluation.entry_request_status),
          class: 'uk-select uk-width-1-1' %>
    </div>
  </div>

  <div class="uk-form-row">
    <label class="uk-form-label">Indoklás:</label>
    <div class="uk-form-controls">
      <%= text_area_tag :explanation, '', class: 'uk-textarea uk-width-1-1' %>
    </div>
  </div>
  <div class="uk-form-row uk-text-center">
    <%= submit_tag 'Mentés', class: 'uk-button'%>
  </div>
<% end %>

app/views/judgements/_point_requests.html.erb
<% stylesheet 'evaluation_table' %>

<div class="uk-grid uk-grid-collapse uk-padding-remove uk-margin-remove">
  <div id="name-list-container">
    <ul class="uk-list uk-list-striped uk-text-bold" id="name-list">
      <% @users.each do |user| %>
        <li class="uk-text-truncate name-list-item" data-user="<%= user.id %>">
          <%= user.link target: :_blank, class: 'uk-link-muted', 'uk-tooltip': '', title: user.nickname %>
        </li>
      <% end %>
      <li>Összegzések:</li>
    </ul>
  </div>
  <div class="uk-overflow-container" id="points-table-container">
    <table class="uk-table uk-table-striped uk-table-hover uk-table-condensed uk-text-center" id="points-table">
      <thead class="rotated">
        <tr>
          <% @evaluation.principles.order(:id).each do |principle| %>
            <th class="sortable-column">
              <div>
                <span>
                  <%= principle.name.truncate 20 %>
                </span>
              </div>
            </th>
          <% end %>
          <th class="sortable-column"><div><span>Szumma felelősség</span></div></th>
          <th class="sortable-column"><div><span>Szumma munka</span></div></th>
          <th class="sortable-column"><div><span>Szumma pont</span></div></th>
          <th><div><span>Belépő</span></div></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr data-user="<%= user.id %>">
            <% @evaluation.ordered_principles.each do |principle| %>
              <td class="col-vertical-border">
                <%= user.single_detail(principle)&.point %>
              </td>
            <% end %>
            <td class="col-vertical-border uk-text-bold">
              <%= user.sum_responsibility_point %>
            </td>
            <td class="col-vertical-border uk-text-bold">
              <%= user.sum_work_point %>
            </td>
            <td class="col-vertical-border uk-text-bold">
              <%= user.sum_all_details %>
            </td>
            <td class="col-vertical-border uk-text-bold">
              <%= Rails.configuration.x.entry_types[user.entry_request&.entry_type] %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot class="uk-text-bold">
        <tr>
          <% @evaluation.ordered_principles.each do |principle| %>
            <td>
              <%= sum_principle_details(@point_details, principle) %>
            </td>
          <% end %>
          <td>
            <%= @evaluation_point_calculator.responsibility_point_sum%>
          </td>
          <td>
            <%= @evaluation_point_calculator.work_point_sum %>
          </td>
          <td>
            <%= @evaluation_point_calculator.all_point_sum %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
  <div class="uk-width-1-1 uk-clearfix">
    <div class="uk-float-right uk-text-bold uk-panel uk-panel-box dark uk-margin-right">
      <div class="uk-clearfix">
        Átlag felelősség:
        <div class="uk-float-right uk-margin-left">
          <%= @evaluation_point_calculator.responsibility_point_average %>
        </div>
      </div>
      <div class="uk-clearfix">
        Átlag munka:
        <div class="uk-float-right uk-margin-left">
          <%= @evaluation_point_calculator.work_point_average %>
        </div>
      </div>
      <div class="uk-clearfix">
        Átlag:
        <div class="uk-float-right uk-margin-left">
          <%= @evaluation_point_calculator.all_point_average %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/judgements/_principles.html.erb
<ul class="uk-list uk-list-striped">
  <li class="uk-grid uk-margin-remove uk-text-bold">
    <div class="uk-width-2-10">
      Megnevezés
    </div>
    <div class="uk-width-3-10">
      Leírás
    </div>
    <div class="uk-width-2-10 uk-text-center">
      Típus
    </div>
    <div class="uk-width-1-10 uk-text-center">
      Max / fő
    </div>
    <div class="uk-width-1-10 uk-text-center">
      Kiosztott
    </div>
  </li>

  <% @evaluation.principles.order(:type, :id).decorate.each do |principle| %>
    <li class="uk-grid uk-margin-remove">
      <div class="uk-width-2-10">
        <%= principle.name %>
      </div>
      <div class="uk-width-3-10">
        <%= principle.description %>
      </div>
      <div class="uk-width-2-10 uk-text-center">
        <%= principle.nice_type %>
      </div>
      <div class="uk-width-1-10 uk-text-center">
        <%= principle.max_per_member %>
      </div>
      <div class="uk-width-1-10 uk-text-center">
        <%= sum_principle_details(@point_details, principle) %>
      </div>
    </li>
  <% end %>
</ul>

app/views/judgements/index.html.erb
<% stylesheet 'admin' %>

<h2 class="uk-h2">
  Értékelések - <%= SystemAttribute.semester.to_readable %>
</h2>

<div id="content-main" class="uk-panel uk-panel-box">

  <div class="uk-width-large-1-2 uk-width-1-1 uk-align-center">
    <%= form_tag(judgements_path, method: :get) do |form| %>
      <%= label_tag(:resort, "Reszort:") %>
      <%= select_tag :resort_id, options_for_select(@resorts.map{|resort| [resort.name, resort.id]}.push(['Egyéb', -1])), include_blank: "Összes"  %>
      <%= submit_tag "Szűrés" %>
    <% end %>
    <ul class="uk-list uk-list-line">
      <li class="uk-clearfix uk-text-bold uk-margin-bottom">
        <div class="uk-float-left">
          Kör
        </div>
        <div class="uk-width-1-4 uk-float-right uk-text-center">
          Pontigénylés
        </div>
        <div class="uk-width-1-4 uk-float-right uk-text-center">
          Belépő igénylés
        </div>
      </li>

      <% @evaluations.each do |evaluation| %>
        <li class="uk-clearfix uk-link-muted">
          <div class="uk-float-left">
            <%= link_to evaluation.group.name, judgement_path(evaluation) %>
          </div>
          <div class="uk-width-1-4 uk-float-right uk-text-center">
            <%= evaluation.nice_point_request_status %>
          </div>
          <div class="uk-width-1-4 uk-float-right uk-text-center">
            <%= evaluation.nice_entry_request_status %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="uk-width-expand uk-text-center uk-margin-top">
    <%= paginate @evaluations %>
  </div>

</div>

app/views/judgements/show.html.erb
<% stylesheet 'admin' %>

<div id="content-main" class="group-container">
  <div class="uk-responsive-width">
    <h1 class="uk-h1">
      <%= @evaluation.group.name %>
      <span class="uk-text-muted"> - <%= Semester.new(@evaluation.semester).to_readable %></span>
    </h1>
    <div class="uk-container-center uk-panel uk-panel-box">

      <% if SystemAttribute.evaluation_season? %>
        <h2>Bírálat</h2>
        <%= render 'form', evaluation: @evaluation %>
      <% end %>

      <ul class="uk-tab uk-margin-top" id="evaluation-tab" data-uk-tab="{connect:'#evaluation-switcher'}">
        <li>
          <a href="#principles">Pontozási elvek</a>
        </li>
        <li class="uk-active">
          <a href="#points">Pontozás</a>
        </li>
        <li>
          <a href="#entries">Belépők</a>
        </li>
        <li>
          <a href="#messages">Üzenetek</a>
        </li>
      </ul>
      <% if policy(@evaluation).show? %>
        <%= link_to 'Értékelés szerkesztése', group_evaluation_path(@evaluation.group, @evaluation), class: 'uk-button uk-button-primary'%>
      <% end %>
      <ul id="evaluation-switcher" class="uk-switcher uk-margin-top">
        <li>
          <%= render 'principles' %>
        </li>
        <li>
          <%= render 'point_requests' %>
        </li>
        <li>
          <%= render 'entry_requests' %>
        </li>
        <li>
          <%= render 'evaluation_messages' %>
        </li>
      </ul>

    </div>
  </div>
</div>