config/routes.rb
Rails.application.routes.draw do

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'
  get '/register', to: 'registration#new'
  post '/register/create', to: 'registration#create', as: :registration
  resources :photos, only: [:show, :update, :edit], constraints: { id: /[^\/]+/ }
  get '/profiles/me/', to: 'profiles#show_self'
  resources :profiles, only: [:show, :update, :edit], constraints: { id: /[^\/]+/ }
  post '/profiles/:id/view-settings', to: 'profiles#update_view_setting', constraints: { id: /[^\/]+/ }, as: :update_view_setting
  patch '/profiles/:id/view-settings', to: 'profiles#update_view_setting', constraints: { id: /[^\/]+/ }
  get '/profile/show/uid/:id', to: redirect('/profiles/%{id}'), constraints: { id: /[^\/]+/ }
  get '/profile/show/virid/:id', to: 'profiles#show_by_id', constraints: { id: /\d+/ }

  get '/photo/raw', to: 'raw_photos#show'
  post '/photo/raw', to: 'raw_photos#update'

  get '/search', to: 'search#search'
  get '/search/suggest', to: 'search#suggest'
  get '/search/suggest_leader', to: 'search#suggest_leader'

  get '/svie/edit', to: 'svie#edit'
  post '/svie/update', to: 'svie#update'
  post '/svie/destroy', to: 'svie#destroy'
  post '/svie/outside', to: 'svie#outside'
  post '/svie/inside', to: 'svie#inside'
  resources :svie, only: %i[index new create]
  get '/svie/pdf', to: 'svie#application_pdf'
  get '/svie/hierarchy', to: 'svie#hierarchy'

  get '/judgement', to: 'judgements#index', as: :judgements
  get '/judgement/:evaluation_id', to: 'judgements#show', as: :judgement
  post '/judgement/:evaluation_id/update', to: 'judgements#update', as: :update_judgement

  root to: redirect('/profiles/me')
  resources :entry_requests do
    get :review, on: :collection
    put :update_review, on: :member
  end
  get 'groups/all', to: 'groups#all', as: :all_groups
  resources :groups, only: [:show, :index, :edit, :update, :create, :new] do
    resources :sub_groups do
      post :join, on: :member
      delete :leave, on: :member
      post :set_admin, on: :member
      resources :sub_group_principles, as: :principles ,only: [:index, :update, :create, :destroy]
      resources :sub_group_evaluations, as: :evaluation do
        get :table
      end
    end
    resources :memberships, only: [:create, :destroy] do
      post '/inactivate', to: 'memberships#inactivate'
      post '/reactivate', to: 'memberships#reactivate'
      post '/accept', to: 'memberships#accept'
      post :withdraw, on: :member
      put '/archive', to: 'memberships#archive'
      put '/unarchive', to: 'memberships#unarchive'
      resources :posts, only: [:index, :create, :destroy]
    end

    get '/group_posts', to: "posts#group_posts", as: :posts
    resources :post_types, only: [:index, :create, :destroy]

    get '/evaluations/current', to: 'evaluations#current'
    resources :evaluations, only: [:index, :show, :edit, :update] do
      resources :principles, only: [:index, :update, :create, :destroy]
      post '/pointdetails/update', to: 'point_details#update'
      resources :point_detail_comments, shallow: true, only: %i[index create update edit destroy]
      post '/entryrequests', to: 'evaluations#submit_entry_request'
      delete '/entryrequests', to: 'evaluations#cancel_entry_request', as: :cancel_entry_request
      post '/entryrequests/update', to: 'entry_requests#update'
      get '/justifications/edit', to: 'justifications#edit'
      post '/justifications/update', to: 'justifications#update'
      get '/table', to: 'evaluations#table'
      post '/pointrequest', to: 'evaluations#submit_point_request'
      delete '/pointrequest', to: 'evaluations#cancel_point_request', as: :cancel_point_request
      post :copy_previous_principles
    end

    get '/messages', to: 'messages#index'
    get '/messages/all', to: 'messages#all'
    post '/messages', to: 'messages#create'
    get '/delegates', to: 'delegates#show'
    post '/delegate', to: 'delegates#create'
    delete '/delegate', to: 'delegates#destroy'
    get '/history', to: 'group_history#show'
  end

  get '/korok/showgroup/id/:id', to: redirect('/groups/%{id}')

  post '/privacies/update', to: 'privacies#update'

  resources :im_accounts, only: [:create, :update, :destroy]

  namespace :admin do
    get 'delegates/count', to: 'delegates#count'
    get 'delegates/export', to: 'delegates#export'
    get 'delegates', to: 'delegates#index'
    post 'delegates/update', to: 'delegates#update'

    resources :svie, only: [:index]
    post '/svie/approve/:id', to: 'svie#approve', as: :svie_approve
    post '/svie/reject/:id', to: 'svie#reject', as: :svie_reject

    resources :rvt_helpers, only: [:index] do
      post :add, on: :member
      post :remove, on: :member
    end
  end

  get '/seasons', to: 'season_admin#index', as: :seasons
  get '/seasons/export_point_history', to: 'season_admin#export_point_history', as: :export_point_history
  get '/seasons/export_entry_requests', to: 'season_admin#export_entry_requests', as: :export_entry_requests
  get '/seasons/export_active_users', to: 'season_admin#export_active_users', as: :export_active_users
  post '/seasons/next', to: 'season_admin#next', as: :next_semester
  post '/seasons/previous', to: 'season_admin#previous', as: :previous_semester
  post '/seasons', to: 'season_admin#update'

  if Rails.env.development? || Rails.env.staging?
    get '/development', to: 'development#index'
    post '/development/impersonate/random', to: 'development#impersonate_someone', as: :impersonate_someone
    post '/development/impersonate/user', to: 'development#impersonate_user', as: :impersonate_user
    post '/development/impersonate/role', to: 'development#impersonate_role', as: :impersonate_role
  end

  get '/services/sync/:id', to: 'auth_sch_services#sync'
  get '/services/sync/:id/memberships', to: 'auth_sch_services#memberships'
  get '/services/entrants/get/:semester/:id', to: 'auth_sch_services#entrants'
  get '/services/entrants/get/:semester/authsch/:id', to: 'auth_sch_services#entrants'

  notify_to :users

end

app/controllers/admin/svie_controller.rb
module Admin
  class SvieController < ApplicationController
    before_action :authorize_user

    def index
      @post_requests = SviePostRequest.all
    end

    def approve
      svie_post_request = SviePostRequest.find(params[:id])
      @user = svie_post_request.user
      @user.update(svie_member_type: svie_post_request.member_type)
      svie_post_request.destroy
    end

    def reject
      svie_post_request = SviePostRequest.destroy(params[:id])
      @user = svie_post_request.user
    end

    private

    def authorize_user
      authorize :application, :manage_SVIE?
    end
  end
end

app/controllers/svie_controller.rb
class SvieController < ApplicationController
  def new
    redirect_to svie_edit_path unless current_user.primary_membership
  end

  def create
    current_user.update(update_params)

    begin
      date_of_birth = params[:date_of_birth].to_date
    rescue ArgumentError
      return redirect_to new_svie_path, alert: t(:bad_date_format)
    else
      current_user.update!(date_of_birth: date_of_birth)
    end

    current_user.svie.create_request(params[:svie_member_type])
    redirect_to svie_edit_path, notice: t(:applied_succesful)
  end

  def edit
    @svie_memberships = current_user.memberships.select { |m| m.group.issvie }
    redirect_back fallback_location: root_url, alert: t(:svie_group_needed) if @svie_memberships.empty?
  end

  def update
    current_user.update(svie_primary_membership: params[:svie][:primary_membership])
    current_user.update(delegated: false)
    return redirect_to profiles_me_path, notice: t(:edit_successful) if current_user.svie.member?

    redirect_to new_svie_path
  end

  def index; end

  def hierarchy
    @parent_groups = Group.select { |group| group.parent.nil? }
  end

  def application_pdf
    unless current_user.svie_post_request
      return redirect_to svie_edit_path, notice: t(:svie_post_request_needed_for_pdf)
    end

    pdf    = GenerateMembershipPdf.new(current_user)
    @user  = current_user
    @title = pdf.title
    @type  = pdf.type

    render layout: false
  end

  def destroy
    join_to(SvieUser::NOT_MEMBER)
  end

  def outside
    join_to(SvieUser::OUTSIDE_MEMBER)
  end

  def inside
    join_to(SvieUser::INSIDE_MEMBER)
  end

  private

  def join_to(member_type)
    return forbidden_page unless current_user.svie.can_join_to?(member_type)

    current_user.svie.create_request(member_type)
    redirect_to svie_edit_path, notice: t(:edit_successful)
  end

  def update_params
    params.permit(:home_address, :mother_name, :place_of_birth, :birth_name, :email)
  end
end

app/views/svie/_hierarchy_tree_item.html.erb
<li>
  <% if group.children.count.zero? %>
    <i class="empty-icon"></i>
  <% else %>
    <i class="uk-link-muted uk-icon-chevron-down"></i>
    <i class="uk-link-muted uk-icon-chevron-up uk-hidden"></i>
  <% end %>

  <%= group.name %>
  <%= link_to icon_tag('uk-icon-external-link', group.name), group_path(group.id),
              class: 'uk-link-muted uk-margin-small-left', target: 'blank' %>

  <ul class="uk-list">
    <% group.children.each do |group| %>
      <%= render 'hierarchy_tree_item', group: group %>
    <% end %>
  </ul>
</li>

app/views/svie/application_pdf.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>PekNext</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'svie_member_request_pdf.css', media: 'all' %>
</head>

<%= button_tag 'Nyomtatás', onclick:'javascript:window.print()',
                            class: 'uk-button uk-button-large uk-button-success uk-align-center no-print' %>

<body>
<table class="uk-table">
  <tr>
    <th class="uk-width-1-3">
      <%= image_tag 'schlogo.png', style: "height:100px" %>
    </th>
    <th class="uk-width-1-3">
      <h2 style="text-align: center;"><%= @title %></h2>
    </th>
    <th class="uk-width-1-3"></th>
  </tr>
</table>

<div>
  <%= render "svie/pdf/#{@type}" %>
</div>
<table class="uk-table">
  <tr class="row">
    <th class= "col">
      Budapest, 20__. ____________ __.
    </th>
    <th class="col">
      <hr>
      Aláírás
    </th>
  </tr>
</table>
<hr>
<p>Tanúsítjuk, hogy jelen nyilatkozat a Nyilatkozó jelenlétünkben írta alá, illetve aláírását a
  sajátjának ismerte el.</p>

<table class="uk-table">
  <tr class="row">
    <th class="col">
      <hr>
      Név
    </th>
    <th class="col">
      <hr>
      Név
    </th>
  </tr>
  <tr class="row">
    <th class="col">
      <hr>
      Lakcím
    </th>
    <th class="col">
      <hr>
      Lakcím
    </th>
  </tr>
  <tr class="row">
    <th class="col">
      <hr>
      Aláírás
    </th>
    <th class="col">
      <hr>
      Aláírás
    </th>
  </tr>
</table>

</body>

</html>

app/views/svie/edit.html.erb
<% stylesheet 'profile' %>

<h1>Elsődleges kör beállítás</h1>
<div id="content-main" class="uk-panel uk-panel-box">
  <div class="uk-width-medium-1-2 uk-container-center uk-overflow-container">
    <h2>Elsődleges kör</h2>
    <%= form_tag svie_update_path, name: 'membershipform', class: 'uk-form uk-margin-top uk-form-horizontal' do %>
      <div class="uk-clearfix">
        <label class="uk-float-left">SVIE köreid:</label>
        <div class="uk-float-right">
          <%= select :svie, :primary_membership, @svie_memberships.map { |m| [m.group.name, m.id] },
          selected: current_user.svie_primary_membership %>
        </div>
      </div>

      <div class="uk-width-1-1 uk-width-medium-1-2 uk-margin uk-align-center">
        <%= submit_tag 'Mentés', class: 'uk-button uk-width-1-1' %>
      </div>
    <% end %>

    <h2>SVIE tagság</h2>
    <div class="uk-alert uk-width-1-1">
      SVIE tagság típusa: <%= Rails.configuration.x.svie_member_types[current_user.svie_member_type] %>
    </div>

    <% if current_user.svie.member? %>

    <div class="uk-grid uk-margin">
      <div class="uk-width-medium-1-1 uk-width-1-1">
        <% if current_user.svie.can_join_to?(SvieUser::NOT_MEMBER) %>
          <div class="uk-grid">
            <div class="uk-width-medium-2-3">
              Tagság megszüntetésének kezdeményezése
            </div>
            <div class="uk-width-medium-1-3">
              <%= button_to 'Kérvény leadása', { action: :destroy },
                class: 'uk-button uk-width-expand uk-button-primary',
                data: { confirm: 'Biztos vagy benne?', disable_with: 'töltés...' } %>
            </div>
          </div>
        <% end %>
        <% if current_user.svie.can_join_to?(SvieUser::OUTSIDE_MEMBER) %>
          <div class="uk-grid">
            <div class="uk-width-medium-2-3">
              Külső taggá válás kezdeményezése
            </div>
            <div class="uk-width-medium-1-3">
              <%= button_to 'Kérvény leadása', { action: :outside },
                class: 'uk-button uk-width-expand uk-button-primary',
                data: { confirm: 'Biztos vagy benne?', disable_with: 'töltés...' } %>
            </div>
          </div>
        <% end %>

        <% if current_user.svie.can_join_to?(SvieUser::INSIDE_MEMBER) %>
          <div class="uk-grid">
            <div class="uk-width-medium-2-3">
              Rendes taggá válás kezdeményezése
            </div>
            <div class="uk-width-medium-1-3">
              <%= button_to 'Kérvény leadása', { action: :inside },
                class: 'uk-button uk-width-expand uk-button-primary',
                data: { confirm: 'Biztos vagy benne?', disable_with: 'töltés...' } %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
    <% end %>
    <% if current_user.svie.in_processing? %>
      <h2>
        <%= Rails.configuration.x.svie_member_types[current_user.svie_post_request.member_type] %>gá válási kérvényed feldolgozás alatt van.
      </h2>
      <p>A folyamat befejezéséhez két lehetőséged van: Ha ki tudod nyomtatni, akkor aláírod a kérvényt és leadod a Schönherz 1719-es irodájában (megtehetitek, hogy többet adtok le egyszerre, nem kell személyesen jelen lenni).</p>
      <p>Ha nem tudod vagy nem akarod kinyomtatni, akkor látogass el nyitvatartási időben a 1719-es irodába, ahol kinyomtatják számodra a papírt.</p>

      <div class="uk-width-1-1 uk-width-medium-1-2 uk-margin uk-align-center">
        <%= button_to "Kitöltött kérvény letöltése", svie_pdf_path,
          method: :get, class: "uk-button uk-button-success uk-width-expand"%>
      </div>
      <div class="uk-text-center">
         <p>vagy</p>
      </div>
      <div class="uk-width-1-1 uk-width-medium-1-2 uk-margin uk-align-center">
        <%= button_to "Üres kérvény letöltése", '/downloads/contract_empty.pdf',
                      method: :get, class: "uk-button uk-button-success uk-width-expand"%>
      </div>
    <% end %>

  </div>
</div>

app/views/svie/hierarchy.html.erb
<div class="uk-height-viewport uk-responsive-width">
  <h1 class="uk-h1">Szervezeti felépítés</h1>
  <div class="uk-container-center uk-panel uk-panel-box">
    <ul class="uk-list uk-list-space" id="hierarchy-tree">
      <% @parent_groups.each do |group| %>
        <%= render 'hierarchy_tree_item', group: group %>
      <% end %>
    </ul>
  </div>
</div>

app/views/svie/index.html.erb
<% stylesheet 'profile' %>

<div id="content-main" class="neutral-container">
  <div class="uk-height-viewport uk-responsive-width">
    <h1 class="uk-h1">Jelentkezés leadása</h1>
    <div class="uk-container-center uk-panel uk-panel-box">
      <h2 class="uk-h2"><%= current_user.full_name %></h2>

      <p>A regisztrációs folyamat befejezéséhez a lent letölthető kérvényt aláírva el kell juttatni a 1719-es gazdasági irodába. Figyeljetek arra oda, hogy a megadott adataitok ne tartalmazzanak hibát, valamint a tanuk is legyenek kitöltve.</p>

      <p>A papírok leadása után az Reszortvezetők Tanácsa adminisztrálni fogja az Egyesületi tagságot a rendszerben.</p>

      <p>További információkat a tagsággal kapcsolatban a https://svie.hu/ weboldalra feltöltött dokumentumok között találhatsz.</p>

      <%= button_to "Kérvény letöltése", svie_pdf_path, method: :get, class: "uk-button uk-button-success uk-align-center"%>
      <%= button_to "Vissza", root_path, method: :get, class: "uk-button uk-align-center"%>
    </div>
  </div>
</div>

app/views/svie/new.html.erb
<% stylesheet 'profile' %>

<div id="content-main" class="neutral-container">
  <div class="uk-height-viewport uk-responsive-width">
    <h1 class="uk-h1">Jelentkezés leadása</h1>
    <div class="uk-container-center uk-panel uk-panel-box">
      <h2 class="uk-h2"><%= current_user.full_name %></h2>
      <h4 class="uk-h4">Jelentkezéshez szükséges adatok</h4>
      <p>Rendes tag: BME-VIK-es aktív, nappali hallgatói jogviszonnyal rendelkező hallgató</p>
      <p>Öreg tag: BME-VIK-en tanult hallgató, aki már nem szeretne aktív lenni az egyesületben</p>
      <p>Külső tag: A fentiekbe nem tartozó személy</p>
      <%= form_tag svie_index_path, method: :post, class: 'uk-form' do %>
        <div class="uk-width-medium-1-2 uk-container-center uk-overflow-container">
          <table class="uk-table">

            <tr>
              <td><%= label_tag :home_address, 'Lakcím:' %></td>
              <td><%= text_field_tag :home_address, current_user.home_address, class: 'uk-input uk-width-expand', required: true %></td>
            </tr>
            <tr>
              <td><%= label_tag :place_of_birth, 'Születési hely:' %></td>
              <td><%= text_field_tag :place_of_birth, current_user.place_of_birth, class: 'uk-input uk-width-expand', required: true %></td>
            </tr>
            <tr>
              <td><%= label_tag :date_of_birth, 'Születési idő:' %></td>
              <td><%= text_field_tag :date_of_birth, current_user.date_of_birth, class: 'uk-width-expand', :data => { 'uk-datepicker' => "{format:'YYYY-MM-DD'}" }, required: true %></td>
            </tr>
            <tr>
              <td><%= label_tag :birth_name, 'Születési név:' %></td>
              <td><%= text_field_tag :birth_name, current_user.birth_name, class: 'uk-input uk-width-expand', required: true %></td>
            </tr>
            <tr>
              <td><%= label_tag :mother_name, 'Anyja neve:' %></td>
              <td><%= text_field_tag :mother_name, current_user.mother_name, class: 'uk-input uk-width-expand', required: true %></td>
            </tr>
            <tr>
              <td><%= label_tag :email, 'Email cím:' %></td>
              <td><%= text_field_tag :email, current_user.email, class: 'uk-input uk-width-expand', required: true %></td>
            </tr>
            <tr>
              <td><%= label_tag :svie_member_type, 'Tagság típusa' %></td>
              <td> <%= select_tag :svie_member_type, options_for_select(Rails.configuration.x.selectable_svie_member_types.invert), class: 'uk-input uk-width-expand' %></td>
            </tr>
          </table>
          <div class="uk-text-center">
            <div class="inline-block">
              <%= submit_tag 'Tovább', class: 'uk-button'  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>