config/routes.rb
Rails.application.routes.draw do

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'
  get '/register', to: 'registration#new'
  post '/register/create', to: 'registration#create', as: :registration
  resources :photos, only: [:show, :update, :edit], constraints: { id: /[^\/]+/ }
  get '/profiles/me/', to: 'profiles#show_self'
  resources :profiles, only: [:show, :update, :edit], constraints: { id: /[^\/]+/ }
  post '/profiles/:id/view-settings', to: 'profiles#update_view_setting', constraints: { id: /[^\/]+/ }, as: :update_view_setting
  patch '/profiles/:id/view-settings', to: 'profiles#update_view_setting', constraints: { id: /[^\/]+/ }
  get '/profile/show/uid/:id', to: redirect('/profiles/%{id}'), constraints: { id: /[^\/]+/ }
  get '/profile/show/virid/:id', to: 'profiles#show_by_id', constraints: { id: /\d+/ }

  get '/photo/raw', to: 'raw_photos#show'
  post '/photo/raw', to: 'raw_photos#update'

  get '/search', to: 'search#search'
  get '/search/suggest', to: 'search#suggest'
  get '/search/suggest_leader', to: 'search#suggest_leader'

  get '/svie/edit', to: 'svie#edit'
  post '/svie/update', to: 'svie#update'
  post '/svie/destroy', to: 'svie#destroy'
  post '/svie/outside', to: 'svie#outside'
  post '/svie/inside', to: 'svie#inside'
  resources :svie, only: %i[index new create]
  get '/svie/pdf', to: 'svie#application_pdf'
  get '/svie/hierarchy', to: 'svie#hierarchy'

  get '/judgement', to: 'judgements#index', as: :judgements
  get '/judgement/:evaluation_id', to: 'judgements#show', as: :judgement
  post '/judgement/:evaluation_id/update', to: 'judgements#update', as: :update_judgement

  root to: redirect('/profiles/me')
  resources :entry_requests do
    get :review, on: :collection
    put :update_review, on: :member
  end
  get 'groups/all', to: 'groups#all', as: :all_groups
  resources :groups, only: [:show, :index, :edit, :update, :create, :new] do
    resources :sub_groups do
      post :join, on: :member
      delete :leave, on: :member
      post :set_admin, on: :member
      resources :sub_group_principles, as: :principles ,only: [:index, :update, :create, :destroy]
      resources :sub_group_evaluations, as: :evaluation do
        get :table
      end
    end
    resources :memberships, only: [:create, :destroy] do
      post '/inactivate', to: 'memberships#inactivate'
      post '/reactivate', to: 'memberships#reactivate'
      post '/accept', to: 'memberships#accept'
      post :withdraw, on: :member
      put '/archive', to: 'memberships#archive'
      put '/unarchive', to: 'memberships#unarchive'
      resources :posts, only: [:index, :create, :destroy]
    end

    get '/group_posts', to: "posts#group_posts", as: :posts
    resources :post_types, only: [:index, :create, :destroy]

    get '/evaluations/current', to: 'evaluations#current'
    resources :evaluations, only: [:index, :show, :edit, :update] do
      resources :principles, only: [:index, :update, :create, :destroy]
      post '/pointdetails/update', to: 'point_details#update'
      resources :point_detail_comments, shallow: true, only: %i[index create update edit destroy]
      post '/entryrequests', to: 'evaluations#submit_entry_request'
      delete '/entryrequests', to: 'evaluations#cancel_entry_request', as: :cancel_entry_request
      post '/entryrequests/update', to: 'entry_requests#update'
      get '/justifications/edit', to: 'justifications#edit'
      post '/justifications/update', to: 'justifications#update'
      get '/table', to: 'evaluations#table'
      post '/pointrequest', to: 'evaluations#submit_point_request'
      delete '/pointrequest', to: 'evaluations#cancel_point_request', as: :cancel_point_request
      post :copy_previous_principles
    end

    get '/messages', to: 'messages#index'
    get '/messages/all', to: 'messages#all'
    post '/messages', to: 'messages#create'
    get '/delegates', to: 'delegates#show'
    post '/delegate', to: 'delegates#create'
    delete '/delegate', to: 'delegates#destroy'
    get '/history', to: 'group_history#show'
  end

  get '/korok/showgroup/id/:id', to: redirect('/groups/%{id}')

  post '/privacies/update', to: 'privacies#update'

  resources :im_accounts, only: [:create, :update, :destroy]

  namespace :admin do
    get 'delegates/count', to: 'delegates#count'
    get 'delegates/export', to: 'delegates#export'
    get 'delegates', to: 'delegates#index'
    post 'delegates/update', to: 'delegates#update'

    resources :svie, only: [:index]
    post '/svie/approve/:id', to: 'svie#approve', as: :svie_approve
    post '/svie/reject/:id', to: 'svie#reject', as: :svie_reject

    resources :rvt_helpers, only: [:index] do
      post :add, on: :member
      post :remove, on: :member
    end
  end

  get '/seasons', to: 'season_admin#index', as: :seasons
  get '/seasons/export_point_history', to: 'season_admin#export_point_history', as: :export_point_history
  get '/seasons/export_entry_requests', to: 'season_admin#export_entry_requests', as: :export_entry_requests
  get '/seasons/export_active_users', to: 'season_admin#export_active_users', as: :export_active_users
  post '/seasons/next', to: 'season_admin#next', as: :next_semester
  post '/seasons/previous', to: 'season_admin#previous', as: :previous_semester
  post '/seasons', to: 'season_admin#update'

  if Rails.env.development? || Rails.env.staging?
    get '/development', to: 'development#index'
    post '/development/impersonate/random', to: 'development#impersonate_someone', as: :impersonate_someone
    post '/development/impersonate/user', to: 'development#impersonate_user', as: :impersonate_user
    post '/development/impersonate/role', to: 'development#impersonate_role', as: :impersonate_role
  end

  get '/services/sync/:id', to: 'auth_sch_services#sync'
  get '/services/sync/:id/memberships', to: 'auth_sch_services#memberships'
  get '/services/entrants/get/:semester/:id', to: 'auth_sch_services#entrants'
  get '/services/entrants/get/:semester/authsch/:id', to: 'auth_sch_services#entrants'

  notify_to :users

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id                       :bigint           not null, primary key
#  archived_members_visible :boolean
#  delegate_count           :integer
#  description              :text
#  founded                  :integer
#  grp_type                 :string(20)
#  head                     :string(48)
#  issvie                   :boolean          default(FALSE), not null
#  maillist                 :string(64)
#  name                     :text             not null
#  state                    :string           default("akt")
#  type                     :string
#  users_can_apply          :boolean          default(TRUE), not null
#  webpage                  :string(64)
#  parent_id                :bigint
#
# Indexes
#
#  groups_grp_id_idx    (id) UNIQUE
#  idx_groups_grp_name  (name)
#  idx_groups_grp_type  (grp_type)
#
# Foreign Keys
#
#  $1  (parent_id => groups.id) ON DELETE => nullify ON UPDATE => cascade
#

class Group < ApplicationRecord
  self.inheritance_column = nil
  has_paper_trail

  alias_attribute :parent, :group

  has_many :sub_groups
  has_many :memberships
  has_many :members, through: :memberships, source: :user
  has_many :post_types
  has_many :evaluations
  has_many :point_requests, through: :evaluations
  has_many :entry_requests, through: :evaluations
  has_many :children, class_name: 'Group', foreign_key: :parent_id
  belongs_to :group, foreign_key: :parent_id, optional: true
  alias own_post_types post_types

  SVIE_ID = 369
  RVT_ID = 146
  KIRDEV_ID = 106
  KB_ID = 1
  SIMONYI_ID = 16
  SSSL_ID = 18
  KSZK_ID = 47
  FALATOZO_ID = 235
  BULIS_ID = 144
  SPORT_ID = 12
  KULTUR_ID = 58
  ERDEKVEDELMI_ID = 427

  RESORTS = [ SIMONYI_ID, SSSL_ID, KSZK_ID, FALATOZO_ID, BULIS_ID, SPORT_ID, KULTUR_ID, ERDEKVEDELMI_ID ]
  scope :resorts, -> { where(id: RESORTS) }

  enum type: {
    group: 'group',
    resort: 'resort',
    team: 'team'
  }, _prefix: :type

  def self.kirdev
    find KIRDEV_ID
  end

  def self.svie
    find SVIE_ID
  end

  def self.rvt
    find RVT_ID
  end

  def self.sssl
    find SSSL_ID
  end

  def inactive_members
    memberships.select(&:inactive?)
  end

  def active_members
    memberships.select(&:active?)
  end

  def archived_members
    memberships.select(&:archived?)
  end

  def newbie_members
    memberships.select(&:newbie?)
  end

  def member?(user)
    user.membership_for(self)
  end

  def user_can_join?(current_user)
    users_can_apply && !member?(current_user)
  end

  def leader
    memberships.includes(posts: [:post_type]).find(&:leader?)
  end

  def post_types
    own_post_types + PostType.where(group: nil)
  end

  def current_delegated_count
    return @currently_delegated_cache if @currently_delegated_cache

    delegates =
      members.includes(:primary_membership).where(delegated: true).select do |user|
        user.primary_membership.group_id == id && user.primary_membership.end_date.nil?
      end
    @currently_delegated_cache = delegates.length
  end

  def can_delegate_more
    current_delegated_count < delegate_count
  end

  def inactive?
    return false if founded_less_than_a_year_ago?

    !active_in_last_two_semesters?
  end

  include ApplicationHelper

  def point_eligible_memberships
    memberships.active.includes(:user)
               .sort { |m1, m2| hu_compare(m1.user.full_name, m2.user.full_name) }
  end

  def accepted_evaluations_by_date
    # According to this measurement, this is the fastest way to reverse sort
    # https://stackoverflow.com/questions/2642182/sorting-an-array-in-descending-order-in-ruby#2651028
    evaluations.select(&:accepted)
               .sort_by(&:date)
               .reverse!
  end

  def has_post_type?(post_type_id)
    post_types.pluck(:id).include?(post_type_id)
  end

  def resort?
    Group.resorts.include?(self)
  end

  def primary_memberships
    memberships.active.includes(posts: :post_type, user: :primary_membership).select(&:primary?)
  end

  def current_evaluation
    evaluations.find_by(semester: SystemAttribute.semester.to_s)
  end

  private

  def founded_less_than_a_year_ago?
    founded.present? && Time.now.year - 1 <= founded
  end

  def active_in_last_two_semesters?
    previous_semester = SystemAttribute.semester.previous
    return true if Evaluation.exists?(group_id: id, date: previous_semester.to_s)

    pre_previous_semester = previous_semester.previous
    Evaluation.exists?(group_id: id, date: pre_previous_semester.to_s)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize_group

  def index
    active_groups = Group.order(:name).reject(&:inactive?)
    active_groups = GroupDecorator.decorate_collection(active_groups)
    @groups = Kaminari.paginate_array(active_groups)
                      .page(params[:page]).per(items_per_page)
  end

  def all
    @groups = Group.order(:name).page(params[:page])
                   .per(items_per_page).decorate
    render :index
  end

  def show
    membership_view_model = MembershipViewModel.new(current_user, params[:id])
    @viewmodel = MembershipViewModelDecorator.decorate(membership_view_model)
    @can_manage_memberships = policy(@viewmodel.group).manage_memberships?

    @memberships = Membership.includes(:post_types)
                             .includes(user: :svie_post_request, posts: :post_type)
                             .where(group_id: params[:id])
    @active_memberships = MembershipCollectionDecorator.new(@memberships.active.page(params[:active_users_page]))
    @inactive_memberships = MembershipCollectionDecorator.new(@memberships.inactive.page(1))
    @archived_memberships = MembershipCollectionDecorator.new(@memberships.archived.page(1))
  end

  def edit; end

  def update
    if current_group.update(update_params)
      redirect_to current_group, notice: t(:edit_successful)
    else
      render :edit
    end
  end

  def new
    @parent_groups = Group.type_resort
  end

  def create
    leader = User.find(params[:selected_user_id])
    group  = CreateGroup.call(create_params, leader, current_user)

    redirect_to group_path(group)
  end

  private

  def update_params
    params.require(:group)
          .permit(:name, :description, :webpage, :founded, :maillist,
                  :users_can_apply, :archived_members_visible)
  end

  def create_params
    params.require(:group).permit(%i[name parent_id issvie type])
  end

  def authorize_group
    authorize current_group, policy_class: GroupPolicy
  end
end

app/views/groups/_active_users.erb
<% active_users(@viewmodel.group) do |member| %>
<div class="uk-width-1-1 uk-width-medium-1-3">
  <div class="uk-panel uk-panel-box dark">

    <div class="uk-panel-title uk-margin-remove uk-grid">
      <div class="uk-width-5-6 uk-padding-remove">
        <%= link_to member.full_name, profile_path(member.screen_name) %>
      </div>
      <% if @viewmodel.leader? %>
      <div class="uk-width-1-6 uk-padding-remove uk-text-right">
        <%= form_tag(group_membership_posts_path(@viewmodel.group.id, member.membership_id), method: :get, class: 'uk-form') do %>
        <%= button_tag "Search", name: nil, class: 'uk-icon-edit uk-button uk-button-small' do %><% end %>
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="uk-panel-body uk-padding-remove">
      <div class="uk-grid uk-grid-collapse">
        <div class="uk-width-1-1">
          <%= member.nickname %>&nbsp;
        </div>
        <div class="uk-width-2-3 uk-padding-small uk-text-bold"><%= member.posts %></div>
        <div class="uk-width-1-3 uk-padding-small uk-text-bold uk-text-right"><%= member.membership_start %> -</div>
        <% if @viewmodel.leader? %>
        <div class="uk-width-1-2 uk-padding-remove uk-align-center">
          <%= button_to "Öreggé avatás", group_membership_inactivate_path(@viewmodel.group.id, member.membership_id),
          method: :post, class: "uk-button uk-button-primary uk-button-small uk-width-auto", remote: true %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/groups/_active_users.html.erb
<% if list? %>

  <ul class="uk-list uk-list-striped uk-margin-large-bottom uk-width-1-1">
    <% active_users(@viewmodel.group) do |member| %>
      <%= render 'group_member_list_item', member: member %>
    <% end %>
  </ul>

<% else %>

  <div class="uk-grid uk-width-1-1 uk-margin-large-bottom" id="active_users_grid" data-uk-grid="{gutter: 20}">
    <% active_users(@viewmodel.group) do |member| %>
      <%= render 'group_member_grid_item', member: member %>
    <% end %>
  </div>

<% end %>

<div id="active_users_paginate">
  <%= paginate @active_users, param_name: 'active_users_page' %>
</div>

app/views/groups/_archived_users.html.erb
<% if list? %>

  <ul class="uk-list uk-list-striped uk-margin-large-bottom uk-width-1-1">
    <% archived_users(@viewmodel.group) do |member| %>
      <%= render 'group_member_list_item', member: member %>
    <% end %>
  </ul>

<% else %>

  <div class="uk-grid uk-width-1-1 uk-margin-large-bottom" id="archived_users_grid" data-uk-grid="{gutter: 20}">
    <% archived_users(@viewmodel.group) do |member| %>
      <%= render 'group_member_grid_item', member: member %>
    <% end %>
  </div>

<% end %>

<div id="archived_users_paginate">
  <%= paginate @archived_users, param_name: 'archived_users_page' %>
</div>

app/views/groups/_group_info.html.erb
<div class="uk-form uk-form-horizontal">
  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Név</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.name %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Alapítási éve</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.founded %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Svie tag</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.svie_state %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Szülő</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.parent %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Weboldal</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.webpage_link %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Levelezőlista</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.maillist %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Körvezető</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.group_leader_link %>
    </div>
  </div>

  <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
    <label class="uk-form-label form-label-required uk-margin-remove">Bemutatkozás</label>
    <div class="uk-form-controls">
      <%= @viewmodel.group.formatted_description %>
    </div>
  </div>

  <% if policy(current_group).edit? %>
    <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
      <label class="uk-form-label form-label-required uk-margin-remove">Elsődleges tagok száma</label>
      <div class="uk-form-controls">
        <%= @viewmodel.primary_members_count %>
      </div>
    </div>
  <% end %>

  <% if @viewmodel.group.inactive? %>
    <div class="uk-form-row uk-margin-small-bottom uk-margin-top-remove">
      <label class="uk-form-label uk-text-bold">A kör valószínűleg inaktív!</label>
    </div>
  <% end %>

</div>

app/views/groups/_group_list_item.html.erb
<li class="uk-panel-box uk-grid uk-grid-collapse dark group-search group-result hover uk-padding-remove" onclick="window.location='<%= group_path(group.id) %>'">
  <div class="thumbnail">
    <%= image_tag "/img/circle.jpg", class: 'uk-thumbnail' %>
  </div>
  <div class="uk-padding-small next-to-thumbnail">
    <div>
      <%= group.link class: 'uk-text-large' %>
    </div>
    <div class="uk-text-break">
      <%= group.truncated_description %>
    <div>
  </div>
</li>

app/views/groups/_group_member_list_item.html.erb
<li class="uk-grid uk-grid-collapse">
  <% if show_images? %>
    <div class="thumbnail">
      <%= image_tag photo_path(member.screen_name), class: 'uk-thumbnail' %>
    </div>
  <% end %>
  <div class="uk-padding-small uk-clearfix next-to-thumbnail">
    <div class="uk-padding-remove uk-float-left uk-text-large uk-width-medium-1-4">
      <%= member.user_link %>
    </div>

    <div class="uk-text-bold uk-float-left"><%= member.posts %></div>

    <% if @can_manage_memberships %>
      <div class="uk-text-right uk-float-right uk-flex uk-text-right">
        <div class="uk-margin-left">
          <%= member.svie_status_icon %>
        </div>
        <div class="uk-margin-left">
          <%= member.edit_post_button(@viewmodel.group) %>
        </div>

        <div class="uk-margin-small-left uk-grid-small uk-width-auto uk-flex">
          <%= member.approve_join_button(@viewmodel.group) %>
          <%= member.reject_join_button(@viewmodel.group) %>
          <%= member.inactivate_user_button(@viewmodel.group) %>
          <%= member.reactivate_user_button(@viewmodel.group) %>
          <%= member.archive_user_button(@viewmodel.group) %>
          <%= member.unarchive_user_button(@viewmodel.group) %>
        </div>
      </div>
    <% end %>
    <div class="uk-text-bold uk-float-right membership-timer"><%= member.membership_time %></div>
  </div>

</li>

app/views/groups/_inactive_users.erb
<% inactive_users(@viewmodel.group) do |member| %>
<div class="uk-width-1-1 uk-width-medium-1-3">
  <div class="uk-panel uk-panel-box dark">
    <div class="uk-panel-title uk-margin-remove">
      <%= link_to member.full_name, profile_path(member.screen_name) %>
    </div>
    <div class="uk-panel-body uk-padding-remove">
      <div class="uk-grid">
        <div class="uk-width-1-1">
          <%= member.nickname %>
        </div>
        <div class="uk-width-1-2 uk-padding-small uk-text-bold"><%= member.posts %></div>
        <div class="uk-width-1-2 uk-padding-small uk-text-bold uk-text-right"><%=l member.membership_start %> - <%=l member.membership_end %></div>
        <% if @viewmodel.leader? %>
        <div class="uk-width-1-2 uk-padding-remove uk-align-center">
          <%= button_to "Újraaktiválás", group_membership_reactivate_path(@viewmodel.group.id, member.membership_id),
          method: :post, class: "uk-button uk-button-primary uk-button-small uk-width-auto", remote: true %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/groups/index.html.erb
<% stylesheet 'groups' %>

<div class="uk-responsive-width uk-margin-large">
  <h1 class="uk-h1">Körök</h1>
  <div class="uk-container-center uk-panel uk-panel-box">
    <p id="notice"><%= notice %></p>

    <% if list? %>

      <ul class="uk-list uk-list-divider uk-list-hover">
        <% @groups.each do |group| %>
          <%= render 'group_list_item', group: group %>
        <% end %>
      </ul>

    <% else %>

      <div class="uk-grid uk-grid-medium" data-uk-grid="{gutter: 15}">
        <% @groups.each do |group| %>
          <%= render 'group_grid_item', group: group %>
        <% end %>
      </div>

    <% end %>
    <div class="uk-width-expand uk-text-center uk-margin-large-top">
      <%= paginate @groups %>
    </div>

  </div>
</div>

app/views/groups/new.html.erb
<%= form_for Group.new, url: groups_path,
             html:           { class: 'uk-form uk-form-horizontal uk-margin-top' } do |f| %>
  <%= render 'form_errors', errors: f.object.errors %>

  <div class="uk-form-row">
    <%= f.label :name, 'Kör neve', class: 'uk-width-1-1 uk-form-label form-label-required' %>
    <%= f.text_field :name, required: true, autofocus: true, class: 'uk-width-1-1 uk-form-large', placeholder: 'Kör neve', autocomplete: "off" %>
  </div>

  <div class="uk-form-row">
    <%= f.label :parent_id, class: 'uk-form-label form-label-required' %>
    <%= f.select :parent_id, @parent_groups.map { |group| [group.name, group.id] },
                 {}, { class: 'uk-width-1-1 uk-select' } %>
  </div>

  <div class="uk-form-row">
    <%= f.label :type, class: 'uk-form-label form-label-required' %>
    <%= f.select :type, Group.types.values,
                 {}, { class: 'uk-width-1-1 uk-select' } %>
  </div>

  <div class="uk-form-row">
    <%= f.label :group_leader, 'Körvez neve', class: 'uk-width-1-1 uk-form-label form-label-required' %>
    <%= text_field_tag :group_leader_name, nil, required: true, autofocus: true, class: 'uk-width-1-1 uk-form-large', placeholder: 'Körvez neve', autocomplete: "off" %>
  </div>

  <div class="uk-form-row">
    <%= f.label :issvie, 'SVIE?', class: 'uk-width-1-1 uk-form-label form-label-required' do %>
      SVIE?
      <%= f.check_box :issvie %>
    <% end %>
  </div>
  <%= hidden_field_tag :selected_user_id, "nil" %>

  <div id="content-main">
    <div class="uk-responsive-width">
      <div class="uk-container-center uk-panel uk-panel-box">
        <div class="uk-grid uk-flex-middle uk-width-1-1 uk-padding-remove uk-margin-remove">
          <li id="user_suggestions" class="uk-width-1-1 uk-padding-remove uk-list-divider">
            Kezdj el gépelni!
          </li>
        </div>
        <a id="show-more-user" , onclick="showMoreUser()" class="uk-button uk-margin-top uk-align-center">Többi
          megjelenítése</a>
        <p id="no-more" class="uk-hidden uk-margin-top uk-align-center">Nincs több találat</p>
      </div>
    </div>
  </div>

  <div class="uk-text-center">
    <div class="inline-block">
      <%= f.submit 'Mehet!', class: 'uk-button uk-button-primary uk-width-1-1 uk-width-medium-1-2 uk-margin-top' %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<% stylesheet 'groups' %>

<div id="content-main" class="group-container">
  <div class="uk-responsive-width">
    <h1 class="uk-h1"><%= @viewmodel.group.name %></h1>
    <div class="uk-container-center uk-panel uk-panel-box">
      <div class="uk-grid">
        <div class="uk-width-medium-3-4">
          <h2 class="uk-h2">Kör adatai</h2>
          <%= render 'group_info'%>
        </div>
        <div class="uk-width-medium-1-4 uk-flex uk-flex-column">
          <%= link_to 'Közösségi történet', group_history_path(@viewmodel.group), class: 'uk-button uk-button-primary uk-width-1-1'%>
          <%= @viewmodel.edit_group_button %>
          <%= @viewmodel.edit_group_delegates_button %>
          <%= @viewmodel.edit_group_post_types_button %>
          <%= @viewmodel.leader_info_button %>
          <%= @viewmodel.join_group_button %>
          <%= @viewmodel.withdraw_membership_button %>
          <%= @viewmodel.evaluation_button %>
          <%= @viewmodel.all_posts_button %>
          <% if current_group.id == Group::SSSL_ID %>
             <%= link_to 'Munkacsoportok', group_sub_groups_path(@viewmodel.group), class: 'uk-button uk-button-primary uk-width-1-1 uk-margin-top uk-button-success'%>
          <% end %>
        </div>
      </div>

      <div class="uk-grid uk-margin-top">
        <div class="uk-width-2-3">
          <h2 class="uk-h2">Tagságok (<%= @viewmodel.all_members_count%>)</h2>
        </div>
      </div>

      <ul class="uk-tab uk-margin" id="membership-tab" data-uk-tab="{connect:'#membership-data'}">
        <li>
          <a class="uk-button uk-text-muted" href="#active">Aktív tagok (<%= @viewmodel.active_members_count %>)</a>
        </li>
        <li>
          <a class="uk-button uk-text-muted" href="#inactive">Öregtagok (<%= @viewmodel.inactive_members_count%>)</a>
        </li>
        <% if @viewmodel.group.archived_members_visible ||  @viewmodel.leader?  %>
          <li>
            <a class="uk-button uk-text-muted" href="#archived">Archivált tagok (<%= @viewmodel.archived_members_count%>)</a>
          </li>
        <% end %>
      </ul>

      <ul id="membership-data" class="uk-switcher">
        <li id="active_users">
          <%= render 'active_users' %>
        </li>
        <li id="inactive_users">
          <%= render 'inactive_users' %>
        </li>
        <% if @viewmodel.group.archived_members_visible || @viewmodel.leader?%>
          <li id="archived_users">
            <%= render 'archived_users' %>
          </li>
        <% end %>
      </ul>

      <%= @viewmodel.leader_info %>

    </div>
  </div>
</div>